#pragma once
#include <cstdint>
// Generated by scripts/build_hlsl_shaders.bat — do not edit manually.
static const uint8_t kShader_xpbd_predict[] = { 0x00 };
static const uint32_t kShader_xpbd_predict_size = 0;
