@echo off
rem Compiles HLSL compute shaders and regenerates src/shaders/hlsl/*.h
rem Run from the repo root on Windows: scripts\build_hlsl_shaders.bat
rem Requires fxc.exe (ships with the Windows SDK / Visual Studio).

setlocal EnableDelayedExpansion

set REPO_ROOT=%~dp0..
set SRC_DIR=%REPO_ROOT%\shaders\hlsl
set OUT_DIR=%REPO_ROOT%\src\shaders\hlsl
set TMP_DIR=%TEMP%\campello_shaders_%RANDOM%
mkdir "%TMP_DIR%"

where fxc >nul 2>&1
if errorlevel 1 (
    echo Error: fxc.exe not found. Open a Visual Studio Developer Command Prompt.
    exit /b 1
)

where python >nul 2>&1
if errorlevel 1 (
    echo Error: python not found. Required for binary-to-header conversion.
    exit /b 1
)

for %%f in ("%SRC_DIR%\*.hlsl") do (
    set "name=%%~nf"
    echo Compiling !name!...
    fxc /nologo /T cs_5_1 /E !name! /O2 /Fo "%TMP_DIR%\!name!.cso" "%%f"
    if errorlevel 1 ( echo   FAILED & goto :cleanup )

    python -c ^
"import sys; data=open(r'%TMP_DIR%\!name!.cso','rb').read(); ^
sym='kShader_!name!'; ^
lines=['#pragma once','#include <cstdint>','// Generated by scripts/build_hlsl_shaders.bat — do not edit manually.',f'static const uint8_t {sym}[] = {{'] + ^
[','.join(f'0x{b:02x}' for b in chunk) for chunk in [data[i:i+12] for i in range(0,len(data),12)]] + ^
['};', f'static const uint32_t {sym}_size = {len(data)};']; ^
open(r'%OUT_DIR%\!name!.h','w').write('\n'.join(lines)+'\n')"
    echo   -^> %OUT_DIR%\!name!.h
)

:cleanup
rmdir /s /q "%TMP_DIR%"
echo Done. Commit the updated headers in src\shaders\hlsl\.
