#!/usr/bin/env bash
# Compiles GLSL compute shaders and regenerates src/shaders/glsl/*.h
# Run from the repo root on Linux/Android: ./scripts/build_glsl_shaders.sh
# Requires glslc (from the Vulkan SDK or apt install glslang-tools).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC_DIR="$REPO_ROOT/shaders/glsl"
OUT_DIR="$REPO_ROOT/src/shaders/glsl"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

if ! command -v glslc &>/dev/null; then
    echo "Error: glslc not found. Install the Vulkan SDK or run: apt install glslang-tools" >&2
    exit 1
fi

for src in "$SRC_DIR"/*.comp; do
    name="$(basename "$src" .comp)"
    echo "Compiling $name..."
    glslc -O -fshader-stage=compute "$src" -o "$TMP_DIR/${name}.spv"

    sym="kShader_${name}"
    size=$(wc -c < "$TMP_DIR/${name}.spv" | tr -d ' ')
    {
        echo "#pragma once"
        echo "#include <cstdint>"
        echo "// Generated by scripts/build_glsl_shaders.sh — do not edit manually."
        echo "static const uint8_t ${sym}[] = {"
        xxd -i "$TMP_DIR/${name}.spv" | grep -v "^unsigned"
        echo "static const uint32_t ${sym}_size = ${size};"
    } > "$OUT_DIR/${name}.h"
    echo "  -> $OUT_DIR/${name}.h (${size} bytes)"
done

echo "Done. Commit the updated headers in src/shaders/glsl/."
