#!/usr/bin/env bash
# Compiles Metal compute shaders and regenerates src/shaders/metal/*.h
# Run from the repo root on macOS: ./scripts/build_metal_shaders.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC_DIR="$REPO_ROOT/shaders/msl"
OUT_DIR="$REPO_ROOT/src/shaders/metal"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

SDK="macosx"
METAL_FLAGS="-std=metal3.0 -O2"

for src in "$SRC_DIR"/*.metal; do
    name="$(basename "$src" .metal)"
    echo "Compiling $name..."
    xcrun -sdk "$SDK" metal $METAL_FLAGS -c "$src" -o "$TMP_DIR/${name}.air"
    xcrun -sdk "$SDK" metallib "$TMP_DIR/${name}.air" -o "$TMP_DIR/${name}.metallib"

    sym="kShader_${name}"
    size=$(wc -c < "$TMP_DIR/${name}.metallib" | tr -d ' ')
    {
        echo "#pragma once"
        echo "#include <cstdint>"
        echo "// Generated by scripts/build_metal_shaders.sh — do not edit manually."
        echo "static const uint8_t ${sym}[] = {"
        xxd -i "$TMP_DIR/${name}.metallib" | grep -v "^unsigned"
        echo "static const uint32_t ${sym}_size = ${size};"
    } > "$OUT_DIR/${name}.h"
    echo "  -> $OUT_DIR/${name}.h (${size} bytes)"
done

echo "Done. Commit the updated headers in src/shaders/metal/."
