#pragma once
#include <cstdint>
// Generated by scripts/build_glsl_shaders.sh — do not edit manually.
static const uint8_t kShader_write_render_transforms[] = { 0x00 };
static const uint32_t kShader_write_render_transforms_size = 0;
