#pragma once
#include <cstdint>
// Generated by scripts/build_glsl_shaders.sh — do not edit manually.
static const uint8_t kShader_xpbd_contacts[] = { 0x00 };
static const uint32_t kShader_xpbd_contacts_size = 0;
