#pragma once
#include <cstdint>
// Generated by scripts/build_metal_shaders.sh — do not edit manually.
static const uint8_t kShader_broadphase_aabb broadphase_pairs xpbd_contacts xpbd_finalize xpbd_predict[] = {

};
static const uint32_t kShader_broadphase_aabb broadphase_pairs xpbd_contacts xpbd_finalize xpbd_predict_size = ;
